// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pkbomgocnpvxylwqlksb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBrYm9tZ29jbnB2eHlsd3Fsa3NiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0ODc1NjEsImV4cCI6MjA2MzA2MzU2MX0.hLImzh5KwPz7LrmrPwOqatNv7YCErBS5qRqsJOQWDmo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);